//
//此文件用于定义客户端主动发起的回应

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.9.2
// source: ack.proto

//
//用于c/s协议解析

package message

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//------------------------   SERVICE_API_LOGIN
type API_LOGIN_ACK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result    ErrCode                   `protobuf:"varint,1,opt,name=Result,proto3,enum=message.ErrCode" json:"Result,omitempty"`
	UserID    int64                     `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Name      string                    `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	CachedMsg []*API_NEW_MESSAGE_NOTIFY `protobuf:"bytes,4,rep,name=CachedMsg,proto3" json:"CachedMsg,omitempty"`
}

func (x *API_LOGIN_ACK) Reset() {
	*x = API_LOGIN_ACK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ack_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *API_LOGIN_ACK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*API_LOGIN_ACK) ProtoMessage() {}

func (x *API_LOGIN_ACK) ProtoReflect() protoreflect.Message {
	mi := &file_ack_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use API_LOGIN_ACK.ProtoReflect.Descriptor instead.
func (*API_LOGIN_ACK) Descriptor() ([]byte, []int) {
	return file_ack_proto_rawDescGZIP(), []int{0}
}

func (x *API_LOGIN_ACK) GetResult() ErrCode {
	if x != nil {
		return x.Result
	}
	return ErrCode_ERR_CODE_FAILED
}

func (x *API_LOGIN_ACK) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *API_LOGIN_ACK) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *API_LOGIN_ACK) GetCachedMsg() []*API_NEW_MESSAGE_NOTIFY {
	if x != nil {
		return x.CachedMsg
	}
	return nil
}

//------------------------   SERVICE_API_SEND
type API_SEND_ACK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result ErrCode `protobuf:"varint,1,opt,name=Result,proto3,enum=message.ErrCode" json:"Result,omitempty"`
}

func (x *API_SEND_ACK) Reset() {
	*x = API_SEND_ACK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ack_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *API_SEND_ACK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*API_SEND_ACK) ProtoMessage() {}

func (x *API_SEND_ACK) ProtoReflect() protoreflect.Message {
	mi := &file_ack_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use API_SEND_ACK.ProtoReflect.Descriptor instead.
func (*API_SEND_ACK) Descriptor() ([]byte, []int) {
	return file_ack_proto_rawDescGZIP(), []int{1}
}

func (x *API_SEND_ACK) GetResult() ErrCode {
	if x != nil {
		return x.Result
	}
	return ErrCode_ERR_CODE_FAILED
}

//------------------------   SERVICE_API_STATS
type API_STATS_ACK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result   ErrCode `protobuf:"varint,1,opt,name=Result,proto3,enum=message.ErrCode" json:"Result,omitempty"`
	JoinTime int64   `protobuf:"varint,2,opt,name=JoinTime,proto3" json:"JoinTime,omitempty"`
}

func (x *API_STATS_ACK) Reset() {
	*x = API_STATS_ACK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ack_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *API_STATS_ACK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*API_STATS_ACK) ProtoMessage() {}

func (x *API_STATS_ACK) ProtoReflect() protoreflect.Message {
	mi := &file_ack_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use API_STATS_ACK.ProtoReflect.Descriptor instead.
func (*API_STATS_ACK) Descriptor() ([]byte, []int) {
	return file_ack_proto_rawDescGZIP(), []int{2}
}

func (x *API_STATS_ACK) GetResult() ErrCode {
	if x != nil {
		return x.Result
	}
	return ErrCode_ERR_CODE_FAILED
}

func (x *API_STATS_ACK) GetJoinTime() int64 {
	if x != nil {
		return x.JoinTime
	}
	return 0
}

//------------------------   SERVICE_API_POPULAR_WORD
type API_POPULAR_WORD_ACK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result ErrCode `protobuf:"varint,1,opt,name=Result,proto3,enum=message.ErrCode" json:"Result,omitempty"`
	Word   string  `protobuf:"bytes,2,opt,name=Word,proto3" json:"Word,omitempty"`
}

func (x *API_POPULAR_WORD_ACK) Reset() {
	*x = API_POPULAR_WORD_ACK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ack_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *API_POPULAR_WORD_ACK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*API_POPULAR_WORD_ACK) ProtoMessage() {}

func (x *API_POPULAR_WORD_ACK) ProtoReflect() protoreflect.Message {
	mi := &file_ack_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use API_POPULAR_WORD_ACK.ProtoReflect.Descriptor instead.
func (*API_POPULAR_WORD_ACK) Descriptor() ([]byte, []int) {
	return file_ack_proto_rawDescGZIP(), []int{3}
}

func (x *API_POPULAR_WORD_ACK) GetResult() ErrCode {
	if x != nil {
		return x.Result
	}
	return ErrCode_ERR_CODE_FAILED
}

func (x *API_POPULAR_WORD_ACK) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

var File_ack_proto protoreflect.FileDescriptor

var file_ack_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x1a, 0x09, 0x65, 0x72, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x09, 0x6e, 0x74, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa4, 0x01, 0x0a, 0x0d, 0x41,
	0x50, 0x49, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x41, 0x43, 0x4b, 0x12, 0x28, 0x0a, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x3d, 0x0a, 0x09, 0x43, 0x61, 0x63, 0x68, 0x65, 0x64, 0x4d, 0x73, 0x67, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x41, 0x50, 0x49, 0x5f, 0x4e, 0x45, 0x57, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f,
	0x4e, 0x4f, 0x54, 0x49, 0x46, 0x59, 0x52, 0x09, 0x43, 0x61, 0x63, 0x68, 0x65, 0x64, 0x4d, 0x73,
	0x67, 0x22, 0x38, 0x0a, 0x0c, 0x41, 0x50, 0x49, 0x5f, 0x53, 0x45, 0x4e, 0x44, 0x5f, 0x41, 0x43,
	0x4b, 0x12, 0x28, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x55, 0x0a, 0x0d, 0x41,
	0x50, 0x49, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x53, 0x5f, 0x41, 0x43, 0x4b, 0x12, 0x28, 0x0a, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0x54, 0x0a, 0x14, 0x41, 0x50, 0x49, 0x5f, 0x50, 0x4f, 0x50, 0x55, 0x4c, 0x41,
	0x52, 0x5f, 0x57, 0x4f, 0x52, 0x44, 0x5f, 0x41, 0x43, 0x4b, 0x12, 0x28, 0x0a, 0x06, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x06, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x57, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x57, 0x6f, 0x72, 0x64, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x65, 0x72, 0x6f, 0x72, 0x65, 0x64, 0x2f, 0x63,
	0x68, 0x61, 0x74, 0x2d, 0x74, 0x65, 0x73, 0x74, 0x2d, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ack_proto_rawDescOnce sync.Once
	file_ack_proto_rawDescData = file_ack_proto_rawDesc
)

func file_ack_proto_rawDescGZIP() []byte {
	file_ack_proto_rawDescOnce.Do(func() {
		file_ack_proto_rawDescData = protoimpl.X.CompressGZIP(file_ack_proto_rawDescData)
	})
	return file_ack_proto_rawDescData
}

var file_ack_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ack_proto_goTypes = []interface{}{
	(*API_LOGIN_ACK)(nil),          // 0: message.API_LOGIN_ACK
	(*API_SEND_ACK)(nil),           // 1: message.API_SEND_ACK
	(*API_STATS_ACK)(nil),          // 2: message.API_STATS_ACK
	(*API_POPULAR_WORD_ACK)(nil),   // 3: message.API_POPULAR_WORD_ACK
	(ErrCode)(0),                   // 4: message.ErrCode
	(*API_NEW_MESSAGE_NOTIFY)(nil), // 5: message.API_NEW_MESSAGE_NOTIFY
}
var file_ack_proto_depIdxs = []int32{
	4, // 0: message.API_LOGIN_ACK.Result:type_name -> message.ErrCode
	5, // 1: message.API_LOGIN_ACK.CachedMsg:type_name -> message.API_NEW_MESSAGE_NOTIFY
	4, // 2: message.API_SEND_ACK.Result:type_name -> message.ErrCode
	4, // 3: message.API_STATS_ACK.Result:type_name -> message.ErrCode
	4, // 4: message.API_POPULAR_WORD_ACK.Result:type_name -> message.ErrCode
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_ack_proto_init() }
func file_ack_proto_init() {
	if File_ack_proto != nil {
		return
	}
	file_err_proto_init()
	file_ntf_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ack_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*API_LOGIN_ACK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ack_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*API_SEND_ACK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ack_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*API_STATS_ACK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ack_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*API_POPULAR_WORD_ACK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ack_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ack_proto_goTypes,
		DependencyIndexes: file_ack_proto_depIdxs,
		MessageInfos:      file_ack_proto_msgTypes,
	}.Build()
	File_ack_proto = out.File
	file_ack_proto_rawDesc = nil
	file_ack_proto_goTypes = nil
	file_ack_proto_depIdxs = nil
}
